- SUPPORT.md
Signed-off-by: Tom Kerkhove kerkhove.tom@gmail.com
> docs: Update links in support strategy

- README.md
Signed-off-by: GitHub <noreply@github.com>
_Provide a description of what has been changed_
> docs: Add 'Releases' to README

- BRANDING.md
- README.md
KEDA was accepted as CNCF Incubation project as per https://github.com/cncf/toc/pull/622
Relates to https://github.com/kedacore/governance/issues/2
> chore: KEDA was accepted as CNCF Incubation project

- MAINTAINERS.md
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Show Codit as previous affiliation for Tom
- ~A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)~
> docs: Show previous affiliation for Tom

- MAINTAINERS.md
Welcome Jorge Turrado Ferrero as a new maintainer!
Relates to #38
> chore: Welcome Jorge Turrado Ferrero as a new maintainer!

- README.md
> docs: Add link to Code of Conduct

- .github/workflows/auto-add-issues-to-project.yml
Project board automation for new issues.
> feat: Project board automation

- README.md
Relates to https://github.com/kedacore/governance/issues/49
> chore: Add CloMonitor badge

- README.md
Signed-off-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>
> Update CLOMonitor badge url

- README.md
Provide link to our roadmap.
Relates to https://github.com/kedacore/governance/issues/48
> chore: Provide link to our roadmap

- MAINTAINERS.md
Update maintainers overview after @jeffhollan moved to Snowflake.
> docs: @jeffhollan moved to Snowflake

- README.md
- SCALERS.md
Provide scaler governance definition
Relates to #5
> docs: Provide scaler governance definition

- SUPPORT.md
> docs: Update Kubernetes version example

- MAINTAINERS.md
Signed-off-by: Jorge Turrado Ferrero <Jorge_turrado@hotmail.es>
> Update my working place

- GOVERNANCE.md
Provide link to scaler governance from general governance of project to make it more discoverable.
Fixes https://github.com/kedacore/governance/issues/90
> feat: Provide link to scaler governance from general governance of project

- CODE_OF_CONDUCT.md
- README.md
Move Code of Conduct to kedacore/governance.
Relates to #86
> feat: Move Code of Conduct to kedacore/governance

- GOVERNANCE.md
Provide guidance on maintainers violating code of conduct.
docs)
Fixes #89
> docs: Provide guidance on maintainers violating code of conduct

- BRANDING.md
- README.md
KEDA is a CNCF Graduated project
Relates to https://github.com/kedacore/governance/issues/63
> chore: KEDA is a CNCF Graduated project

- MAINTAINERS.md
> Change Zbynek's company

- GOVERNANCE.md
Provide guidance on when maintainers will (not) approve a PR
Closes https://github.com/kedacore/governance/issues/94
> Provide guidance on when maintainers will (not) approve a PR

- MAINTAINERS.md
Ahmes ElSayed is stepping down
Closes https://github.com/kedacore/governance/issues/108
> chore: Ahmes ElSayed is stepping down

- MAINTAINERS.md
> remove Affiliation column from Alumni section

- .github/CODEOWNERS
Relates: https://github.com/kedacore/governance/issues/108
> remove @ahmelsayed

- COMMUNITY.md
- README.md
Recognizing community members with Credly badges
Relates to https://github.com/kedacore/governance/issues/58
> feat: Recognizing community members with Credly badges

- MAINTAINERS.md
Welcome Jan Wozniak as a new KEDA maintainer!
Relates: #114
> Welcome Jan Wozniak as a new KEDA maintainer!

- .github/CODEOWNERS
Relates https://github.com/kedacore/governance/issues/115 https://github.com/kedacore/governance/issues/117
> add Jan, remove Tom

- GOVERNANCE.md
- MEMBERS.md
A follow up PR from the discussion in https://github.com/kedacore/governance/pull/125
> Change repository contributor role to reviewer role
